use_frameworks!
platform :ios, '9.0'

target 'OhmageOMHSDK_Example' do

  pod 'OhmageOMHSDK', :path => '../'
  pod 'OhmageOMHSDK/RKSupport', :path => '../'
  pod 'OhmageOMHSDK/RSTBSupport', :path => '../'
  pod 'OhmageOMHSDK/RSRPSupport', :path => '../'

  pod 'ResearchKit', '~> 1.4'

  target 'OhmageOMHSDK_Tests' do
    inherit! :search_paths


  end
end
